import { spawn } from 'node:child_process';
import path from 'node:path';

export function buildBranchName(incomingErrorId) {
  return `ai-fix/error-${incomingErrorId}-${Date.now()}`;
}

function runGit(args, cwd) {
  return new Promise((resolve, reject) => {
    const child = spawn('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] });
    let stdout = '';
    let stderr = '';

    child.stdout.on('data', (chunk) => {
      stdout += chunk.toString();
    });

    child.stderr.on('data', (chunk) => {
      stderr += chunk.toString();
    });

    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) {
        resolve({ stdout: stdout.trim(), stderr: stderr.trim() });
        return;
      }

      reject(new Error(`git ${args.join(' ')} failed (${code}): ${stderr || stdout}`));
    });
  });
}

async function createPullRequestViaApi({ owner, repo, token, title, body, head, base }) {
  const response = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28'
    },
    body: JSON.stringify({
      title,
      body,
      head,
      base
    })
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`github PR create failed: ${response.status} ${text}`);
  }

  return response.json();
}

export async function createPullRequest({
  owner,
  repo,
  token,
  baseBranch,
  branchName,
  incomingErrorId,
  sandboxRoot,
  repoDir,
  llmSuggestion,
  fixNote,
  checksOutput,
  errorMessage,
  stackTrace,
  fixApplied = false
}) {
  const hasPlaceholder = [owner, repo, token].some((value) =>
    String(value || '').toLowerCase().includes('replace_me')
  );

  if (!owner || !repo || !token || hasPlaceholder) {
    return {
      prUrl: null,
      note: 'missing/placeholder GitHub owner/repo/token, skipping PR creation'
    };
  }

  if (!fixApplied) {
    return {
      prUrl: null,
      note: 'no source patch was applied, skipping PR creation'
    };
  }

  const targetRepoDir = repoDir || path.join(sandboxRoot, repo);

  if (!repoDir) {
    await fs.rm(targetRepoDir, { recursive: true, force: true });
    await fs.mkdir(sandboxRoot, { recursive: true });
    const remote = `https://x-access-token:${token}@github.com/${owner}/${repo}.git`;
    await runGit(['clone', remote, targetRepoDir], process.cwd());
  }

  await runGit(['checkout', '-b', branchName], targetRepoDir);

  await runGit(['add', '.'], targetRepoDir);

  const status = await runGit(['status', '--porcelain'], targetRepoDir);
  if (!status.stdout) {
    return {
      prUrl: null,
      note: 'no file changes detected, skipping PR creation'
    };
  }

  await runGit(['config', 'user.name', 'AI Agent'], targetRepoDir);
  await runGit(['config', 'user.email', 'ai-agent@local'], targetRepoDir);
  await runGit(['commit', '-m', `fix: ai patch for error ${incomingErrorId}`], targetRepoDir);
  await runGit(['push', '-u', 'origin', branchName], targetRepoDir);

  const pr = await createPullRequestViaApi({
    owner,
    repo,
    token,
    title: `AI fix: incident ${incomingErrorId}`,
    body: [
      'Automated PR generated by AI Agent worker.',
      '',
      `- Error ID: ${incomingErrorId}`,
      `- Branch: ${branchName}`,
      `- Fix note: ${fixNote || 'patch applied'}`,
      '',
      '## Error',
      errorMessage || 'n/a',
      '',
      '## Stack Trace',
      '```',
      stackTrace || 'n/a',
      '```',
      '',
      '## Checks',
      checksOutput ? checksOutput.slice(0, 1500) : 'n/a',
      '',
      '## LLM Suggestion (truncated)',
      llmSuggestion ? llmSuggestion.slice(0, 1200) : 'n/a'
    ].join('\n'),
    head: branchName,
    base: baseBranch
  });

  return {
    prUrl: pr.html_url,
    note: `PR created successfully: ${pr.html_url}`
  };
}
